# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# Code for building on Linux & Mac with multiple R versions


# Code for Deploying Package Site using pkgdown
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

# Code to run Code Coverage post builds
after_success:
  - Rscript -e 'covr::codecov()'
